mybot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10  

  # mobile_base_controller:
  #   type: "diff_drive_controller/DiffDriveController"
  #   left_wheel: 'left_wheel_hinge'
  #   right_wheel: 'right_wheel_hinge'
  #   pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  #   twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  LF_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_wheel_hinge
    pid: {p: 0.5, i: 0.00, d: 0.0}

  RF_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_wheel_hinge
    pid: {p: 0.0, i: 0.00, d: 0.0}

  LR_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_wheel_rear_hinge
    pid: {p: 0.0, i: 0.00, d: 0.0}

  RR_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_wheel_rear_hinge
    pid: {p: 0.0, i: 0.00, d: 0.0}
